weights: ''
cfg: models/custom_yolov5.yaml
data: data.yaml
hyp:
  anchor_t: 4.0
  box: 0.05
  cls: 0.3
  cls_pw: 1.0
  copy_paste: 0.1
  degrees: 0.0
  fl_gamma: 0.0
  fliplr: 0.5
  flipud: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  iou_t: 0.2
  lr0: 0.01
  lrf: 0.2
  mixup: 0.1
  momentum: 0.937
  mosaic: 1.0
  obj: 0.7
  obj_pw: 1.0
  perspective: 0.0
  scale: 0.5
  shear: 0.0
  translate: 0.2
  warmup_bias_lr: 0.1
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  weight_decay: 0.0005
epochs: 300
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: yolov5\data\hyps
resume_evolve: null
bucket: ''
cache: ram
image_weights: false
device: cpu
multi_scale: false
single_cls: false
optimizer: Adam
sync_bn: false
workers: 8
project: runs/train
name: microplastic_detection
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 50
freeze:
- 0
save_period: 10
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: runs\train\microplastic_detection
